### ISSUE TITLE
A BUG in makefile

### ISSUE THREAD

**Issue by yyy1mu** [leafee98/ParseVmess#3]
in makefile，
`[ -d ./src/include/ ] || mkdir -p ./src/include/ `
should be
`[ -d ./src/include/myBase64 ] || mkdir -p ./src/include/myBase64`

when i build the macos version,  i found the bugs

**Comment by yyy1mu** [comment]
when i git submoudle ，i found i have permission problem。then i directly git clone that respo
我发现在我同步子项目依赖时候也出现了权限问题。然后我直接git clone那个项目。如果以后有人使用这个项目注意这个问题。项目在macos上可用

**Comment by leafee98** [comment]
Thanks fo your issue, but this project is a practice for me to learning cpp. Many of it is not the best practice.

I fixed the bug in this issue, and it should work now on Linux with g++.

If you are looking for a proxy client or a subscribtion manager for terminal, there's https://github.com/mzz2017/gg which may help you.

**Comment by leafee98** [comment]
By the way, it's still outdated now, and doesn't support many modern proxy protocol and subscription format, it shouldn't be used more than for practicing cpp.

By another way, the submodule myBase64 is not a robust implement for base64 encoding and decoding ;)
